### ISSUE TITLE
/*/thruster_command is geometry_msgs/Wrench

### ISSUE THREAD

**Issue by patrickelectric** [freefloating-gazebo/bluerov_ffg#2]
After `roslaunch bluerov_ffg thruster_cmd.launch`.

The gui do not work, when I try to use rospub I receive this message.

```sh
rostopic pub -1 /brov/thruster_command sensor_msgs/JointState '{header: auto, name: ['thr1'], position: [90000], velocity: [], effort: []}'

[WARN] [1510684898.008984]: Could not process inbound connection: topic types do not match: [geometry_msgs/Wrench] vs. [sensor_msgs/JointState]{'topic': '/brov/thruster_command', 'tcp_nodelay': '0', 'md5sum': '4f539cf138b23283b520fd271b567936', 'type': 'geometry_msgs/Wrench', 'callerid': '/gazebo'}
```

Update: [log](https://pastebin.com/yRjJ0aNk)

**Comment by oKermorgant** [comment]
I have just pushed a new version. It is compatible with the latest freefloating_gazebo that handles automatically differences between thruster-based versus wrench-based control.
Depending on the control type, Gazebo expects wither Jointstate (thruster efforts) or Wrench (body wrench) on the command topic. It could still be improved but works pretty fine as soon as the launch file loads the correct configuration file. 

Note that for the BlueROV, wrench-based control (ie. position or velocity tracking) is still in development (robot modeling + PID gain tuning) and is done by students at Centrale Nantes.

**Comment by patrickelectric** [comment]
@oKermorgant ty for reply.

`roslaunch bluerov_ffg thruster_cmd.launch` still not working after this update.
My focus is to control each thruster independently, I can see the /brov/thruster_command but I don't know how to send Wrench messages that work with independently thrusters, sending JointState do not work, I am sending the same message that joint_state_publisher (that doesn't work either).

**Comment by patrickelectric** [comment]
The problem appear only when roscore or any other topic is running.
To reproduce: run roscore, run launch, close launch, run again launch.
The wrench message will appear again and joint_state_publisher will not work.

**Comment by oKermorgant** [comment]
All right thanks for the details, you can update both freefloating_gazebo and bluerov_ffg to the last commit. Indeed a re-run was preventing Gazebo from detecting thruster control.
